name: 'ci'

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Lint
        run: |
          npm install
          npm run lint
